### ISSUE TITLE
Have Links in the Widget Open in a New Window.

### ISSUE THREAD

**Issue by thedude83** [humhub/humhub-modules-linklist#4]
If the link were to say have the target set to _blank then they would open in a new tab/window. This is how it is set up on the actual link list but not on the widget.

**Comment by thedude83** [comment]
I've already located the code to fix this. How can I contribute to code? I'm new to github so I don't know how it works.

**Comment by luke-** [comment]
Thanks for contributing & sorry for the late reply!
